# Generated by Django 4.2.21 on 2025-05-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_comment='상품 코드', max_length=255)),
                ('name', models.CharField(db_comment='상품명', max_length=255)),
                ('price', models.DecimalField(db_comment='가격', decimal_places=2, max_digits=10)),
                ('discount_rate', models.DecimalField(db_comment='할인율', decimal_places=2, max_digits=10)),
                ('status', models.CharField(db_comment='판매 상태', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='등록 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일자')),
            ],
            options={
                'db_table': 'books',
                'db_table_comment': '도서 테이블',
            },
        ),
        migrations.CreateModel(
            name='PublishInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(db_comment='출판사명', max_length=255)),
                ('published_date', models.DateField(db_comment='출간일')),
                ('status', models.CharField(db_comment='노출 상태', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='등록 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일자')),
                ('book_code', models.OneToOneField(db_comment='상품 코드', on_delete=django.db.models.deletion.CASCADE, related_name='publish_info', to='product.book')),
            ],
            options={
                'db_table': 'publishers',
                'db_table_comment': '출판사 테이블',
            },
        ),
        migrations.CreateModel(
            name='BookFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(db_comment='도서 타입', max_length=255)),
                ('status', models.CharField(db_comment='노출 상태', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='등록 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일자')),
                ('book_code', models.ForeignKey(db_comment='상품 코드', on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='product.book')),
            ],
            options={
                'db_table': 'product_features',
                'db_table_comment': '도서 타입 테이블',
            },
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_comment='분야', max_length=255)),
                ('description', models.TextField(db_comment='상품 설명')),
                ('status', models.CharField(db_comment='노출 상태', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='등록 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일자')),
                ('book_code', models.OneToOneField(db_comment='상품 코드', on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='product.book')),
            ],
            options={
                'db_table': 'book_details',
                'db_table_comment': '도서 상세 테이블',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(db_comment='저자명', max_length=255)),
                ('status', models.CharField(db_comment='노출 상태', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='등록 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일자')),
                ('book_code', models.OneToOneField(db_comment='상품 코드', on_delete=django.db.models.deletion.CASCADE, related_name='author', to='product.book')),
            ],
            options={
                'db_table': 'authors',
                'db_table_comment': '저자 테이블',
            },
        ),
    ]
