# Generated by Django 4.2.21 on 2025-06-02 08:19

import apps.pricing.domain.value_objects
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'PERCENTAGE'), ('FIXED', 'FIXED')], db_comment='할인 유형', max_length=20)),
                ('value', models.DecimalField(db_comment='할인율 또는 정액 값', decimal_places=2, max_digits=10)),
                ('target_type', models.CharField(choices=[('PRODUCT', 'PRODUCT'), ('USER', 'USER'), ('ALL', 'ALL')], db_comment='할인 정책 타입', default=apps.pricing.domain.value_objects.TargetType['ALL'], max_length=20)),
                ('is_active', models.BooleanField(db_comment='활성 상태', default=True)),
                ('minimum_purchase_amount', models.DecimalField(db_comment='최소 구매 금액', decimal_places=2, default=0, max_digits=10)),
                ('effective_start_at', models.DateTimeField(db_comment='시작 일자')),
                ('effective_end_at', models.DateTimeField(db_comment='종료 일자')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'discount_policies',
                'db_table_comment': '할인 정책 테이블',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='사용자 이름', max_length=255)),
            ],
            options={
                'db_table': 'users',
                'db_table_comment': '사용자 테이블',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_auto_discount', models.BooleanField(default=False)),
                ('apply_priority', models.IntegerField(default=0)),
                ('effective_start_at', models.DateTimeField()),
                ('effective_end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.discountpolicy')),
                ('target_product_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.book', to_field='code')),
                ('target_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.user')),
            ],
            options={
                'db_table': 'promotions',
                'db_table_comment': '프로모션 테이블',
            },
        ),
        migrations.CreateModel(
            name='DiscountTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False)),
                ('apply_priority', models.IntegerField(db_comment='적용 우선순위')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_policy', models.ForeignKey(db_comment='할인 정책', on_delete=django.db.models.deletion.CASCADE, to='pricing.discountpolicy')),
                ('target_product_code', models.ForeignKey(db_comment='상품에 적용되는 경우 값 있음', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.book', to_field='code')),
                ('target_user', models.ForeignKey(db_comment='사용자에 적용되는 경우 값 있음', null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.user')),
            ],
            options={
                'db_table': 'discount_targets',
                'db_table_comment': '할인 정책 타겟 테이블',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_comment='쿠폰 코드', max_length=255)),
                ('name', models.CharField(db_comment='쿠폰 이름', max_length=255)),
                ('valid_until', models.DateTimeField(db_comment='유효 기간')),
                ('status', models.CharField(db_comment='사용 상태', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='등록 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일자')),
                ('discount_policy', models.ForeignKey(db_comment='할인 정책', on_delete=django.db.models.deletion.CASCADE, to='pricing.discountpolicy')),
            ],
            options={
                'db_table': 'coupons',
                'db_table_comment': '쿠폰 테이블',
            },
        ),
    ]
